### ISSUE TITLE
java.lang.NoClassDefFoundError on server join

### ISSUE THREAD

**Issue by CrystallDEV** [InventivetalentDev/PacketListenerAPI#72]
## What steps will reproduce the problem?  
1. start the server with this plugin and maybe glow api
2. join the server
3. receive error

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Can't join the server anymore, but the version is 3.7.8

## What Spigot version are you using? *Type /version*  
Paper 1.16.2 (#147)

## What plugins are you using? *Type /plugins*  
GlowAPI, WorldEdit, PacketListenerAPI

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/rWSd4xgi

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Error happened after upgrading to 1.16.2 and updating PacketListenerAPI from 3.7.7 to 3.7.8. Previous version had an error on server start

**Comment by InventivetalentDev** [comment]
Seems fine for me, might be more of an issue with GlowAPI

**Comment by CrystallDEV** [comment]
Solved with the latest commits and the resulting snapshot on the GlowAPI
