### ISSUE TITLE
PacketListenerAPI is not working with Minecraft 1.18

### ISSUE THREAD

**Issue by Laurenshup** [InventivetalentDev/PacketListenerAPI#110]
Since Minecraft has changed their Java packages, all class have been reordered in other packages. This results in the NMS resolver not working anymore.

**Comment by ErythroCraft** [comment]
Hello I was wandering about NMS content.

How to use nms? Check out this site.

https://www.spigotmc.org/threads/nms-in-1-18.537406/

**Comment by ErythroCraft** [comment]
Sorry. I forgot to upload the bug to see what's happen.

https://pastebin.com/LQvmwHuJ

**Comment by kccricket** [comment]
Stacktrace.

```
[22:30:48] [Server thread/INFO]: [PacketListenerApi] Loading PacketListenerApi v3.9.9-SNAPSHOT
[22:30:48] [Server thread/INFO]: [PacketListenerApi] [STDOUT] [ReflectionHelper/MinecraftVersion] I am loaded from package org.inventivetalent.packetlistener.reflection.minecraft
[22:30:48] [Server thread/WARN]: Nag author(s): '[inventivetalent]' of 'PacketListenerApi' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[22:30:48] [Server thread/ERROR]: [PacketListenerApi] [STDERR] [ReflectionHelper/MinecraftVersion] Failed to find version enum for 'org.bukkit.craftbukkit.v1_18_R2'/'v1_18_R2'
[22:30:48] [Server thread/INFO]: [PacketListenerApi] [STDOUT] [ReflectionHelper/MinecraftVersion] Generating dynamic constant...
[22:30:48] [Server thread/INFO]: [PacketListenerApi] [STDOUT] [ReflectionHelper/MinecraftVersion] Injected dynamic version v1_18_R2 (#11802).
[22:30:48] [Server thread/INFO]: [PacketListenerApi] [STDOUT] [ReflectionHelper/MinecraftVersion] Please inform inventivetalent about the outdated version, as this is not guaranteed to work.
[22:30:48] [Server thread/INFO]: [PacketListenerApi] [STDOUT] [ReflectionHelper/MinecraftVersion] Version is v1_18_R2 (11802)
[22:30:48] [Server thread/ERROR]: [PacketListenerApi] [STDERR] [ReflectionHelper] Failed to find version enum for 'org.bukkit.craftbukkit.v1_18_R2'/'v1_18_R2'
[22:30:48] [Server thread/INFO]: [PacketListenerApi] [STDOUT] [ReflectionHelper] Generating dynamic constant...
[22:30:48] [Server thread/WARN]: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='constructorAccessor', types=[]}] in class class java.lang.reflect.Constructor
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:252)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:12)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:63)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.resolve(FieldResolver.java:69)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.newEnumInstance(Minecraft.java:289)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft$Version.getVersion(Minecraft.java:257)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:40)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:26)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:17)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(ChannelAbstract.java:22)
[22:30:48] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[22:30:48] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:37)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:9)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:53)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:29)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(ChannelInjector.java:41)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:28)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
[22:30:48] [Server thread/WARN]:        at PacketListenerAPI_v3.9.9-SNAPSHOT.jar//org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:16)
[22:30:48] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423)
[22:30:48] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
[22:30:48] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1165)
[22:30:48] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[22:30:48] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:30:48] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] null initializing PacketListenerApi v3.9.9-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:26) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:17) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(ChannelAbstract.java:22) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:37) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:9) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:53) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:29) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(ChannelInjector.java:41) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:28) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:16) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.18.2.jar:git-Paper-235]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_18_R2.Entity', types=[]}, ResolverQuery{name='net.minecraft.server.v1_18_R2.Entity', types=[]}]
        at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:56) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_18_R2.Entity', types=[]}, ResolverQuery{name='net.minecraft.server.v1_18_R2.Entity', types=[]}]
        at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:42) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:9) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:63) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:29) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:28) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:53) ~[PacketListenerAPI_v3.9.9-SNAPSHOT.jar:?]
        ... 18 more
```

**Comment by Drc-DEV** [comment]
not working on 1.18.2

**Comment by InventivetalentDev** [comment]
try https://github.com/InventivetalentDev/PacketListenerAPI/releases/tag/3.9.10-SNAPSHOT plz

**Comment by Drc-DEV** [comment]
> try https://github.com/InventivetalentDev/PacketListenerAPI/releases/tag/3.9.10-SNAPSHOT plz

This version loads, but GlowAPI spams errors

`[16:16:52 WARN]: [GlowAPI] Task #5025 for GlowAPI v1.5.2-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: Could not initialize class org.inventivetalent.glow.reflection.minecraft.Minecraft
        at org.inventivetalent.glow.reflection.resolver.minecraft.OBCClassResolver.resolve(OBCClassResolver.java:15) ~[GlowAPI-1.5.2.jar:?]
        at org.inventivetalent.glow.GlowAPI.getEntityById(GlowAPI.java:654) ~[GlowAPI-1.5.2.jar:?]
        at org.inventivetalent.glow.GlowAPI$1.lambda$onSend$0(GlowAPI.java:587) ~[GlowAPI-1.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-242]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-242]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by AlisaShturm** [comment]
This version, ( 3.9.10-Snapshot ) spams errors: 

[08:01:57 ERROR]: [ReflectionHelper/MinecraftVersion] Failed to find version enum for 'org.bukkit.craftbukkit.v1_18_R2'/'v1_18_R2'
[08:01:57 INFO]: [ReflectionHelper/MinecraftVersion] Generating dynamic constant...
[08:01:57 INFO]: [ReflectionHelper/MinecraftVersion] Injected dynamic version v1_18_R2 (#11802).
[08:01:57 INFO]: [ReflectionHelper/MinecraftVersion] Please inform inventivetalent about the outdated version, as this is not guaranteed to work.
[08:01:57 INFO]: [ReflectionHelper/MinecraftVersion] Version is v1_18_R2 (11802)
[08:01:57 ERROR]: [ReflectionHelper] Failed to find version enum for 'org.bukkit.craftbukkit.v1_18_R2'/'v1_18_R2'
[08:01:57 INFO]: [ReflectionHelper] Generating dynamic constant...
[08:01:57 WARN]: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='constructorAccessor', types=[]}] in class class java.lang.reflect.Constructor
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.resolve(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.newEnumInstance(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft$Version.getVersion(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(Unknown Source)
[08:01:57 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[08:01:57 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.ChannelInjector.inject(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.PacketListenerAPI.load(Unknown Source)
[08:01:57 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//com.lahuca.botsentry.spigot.BotSentrySpigot.onEnable(Unknown Source)
[08:01:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:01:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[08:01:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[08:01:57 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[08:01:57 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[08:01:57 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[08:01:57 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[08:01:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[08:01:57 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[08:01:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[08:01:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MistakingManx** [comment]
Bump, 1.21.7, same errors on load as before.
